# Generated by Django 3.1.4 on 2021-01-01 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rackapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ip', models.GenericIPAddressField()),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blades', to='rackapp.rack')),
            ],
            options={
                'verbose_name_plural': '[02 Blade]',
            },
        ),
    ]
