# Generated by Django 3.1.4 on 2021-01-02 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bladeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blade',
            options={'verbose_name_plural': 'Blades'},
        ),
    ]
