# Generated by Django 3.1.4 on 2021-01-02 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bladeapp', '0002_auto_20210102_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ip', models.GenericIPAddressField()),
                ('blade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='bladeapp.blade')),
            ],
            options={
                'verbose_name_plural': 'Slots',
            },
        ),
    ]
